### PR TITLE
[FEATURE] Add support for TYPO3 v12.4 LTS

### PR DESCRIPTION
**Pull request by eliashaeussler**
This PR adds support for TYPO3 v12.4. The following code changes were made:

- Drop support for TYPO3 v12 sprint releases
- Support TYPO3 testing framework v7 and v8
- Support for Doctrine DBAL 3.x (required with TYPO3 >= 12)
- Event listener instead of hook for flex form modification (ref: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-97449-RemovedHookForModifyingFlexFormParsing.html)
- Skip `TCEforms` property in flex forms (ref: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-97126-RemoveTCEformsArrayKeyInFlexForm.html)

I added additional support for PHP 8.2 in the first place, but removed it later since [Travis does not seem to support PHP 8.2 yet](https://travis-ci.community/t/php-8-2-support/13401).

### CODE REVIEW

**Comment by mbrodala** [comment]
Fixes https://github.com/IchHabRecht/filefill/issues/70

**Comment by mbrodala** [comment]
@IchHabRecht can you have a look at this?

**Comment by IchHabRecht** [comment]
Hi @eliashaeussler,

Thank you for your pull request. I released a new version that is compatible to TYPO3 12.4 today without any additional adjustments. In your changes I don't like the usage of the deprecated class in the new EventListener. That would mean it needs additional work when the class could be removed. Thus I think your pull request needs some adjustments. If you want you can take care but I can do it (ones a new major version of TYPO3 is released) as well.

**Comment by eliashaeussler** [comment]
Seems to be obsolete now, will close the PR.

**Pull request closed without merging**
