### PR TITLE
Remove use of TCEForms key in FlexForm configs

### PR DESCRIPTION
**Pull request by maikusch**
See TYPO3 core change [97126](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-97126-RemoveTCEformsArrayKeyInFlexForm.html).

Resolves: #72

### CODE REVIEW

**Comment by IchHabRecht** [comment]
Hi @maikusch 

If I see it correctly, this change is already a part of the branch https://github.com/IchHabRecht/filefill/tree/bugfix/typo3-12-4-be-support

**Comment by maikusch** [comment]
Hi @IchHabRecht 

I think i know what you mean. In your last commit you added an Eventlistener for FlexForm manipulation. This seems to be ok. The error, described in the issue occurs in the FlexFormHook. Because this hook still uses the TCEForms key.

**Comment by sat-hub** [comment]
I can confirm that this MR solves the problem. I installed "dev-bugfix/typo3-12-4-be-support" via Composer and changed these three files manually. Then I can successfully edit storages again and set tx_filefill_* in BE editor.

**Comment by jokumer** [comment]
In my case the problem is solved with bugfix version as Nicole mentioned
- install "dev-bugfix/typo3-12-4-be-support" via Composer
- TYPO3 v12.4.10
- no configuration beforehand

**Pull request closed without merging**
