### PR TITLE
[FEATURE] Allow storage configuration in TYPO3_CONF_VARS

### PR DESCRIPTION
**Pull request by IchHabRecht**
Resolves: #1

### CODE REVIEW

**Comment by knusperpixel** [comment]
Can you merge this?

**Comment by IchHabRecht** [comment]
Did you try it? Does it work?

**Comment by knusperpixel** [comment]
image
Yes! It seems to work just fine...

**Comment by IchHabRecht** [comment]
Please note: for compatibility reasons I needed to change the 'domain' configuration.

**Pull request merged**
